import { Box, Container, Text, Flex } from "@chakra-ui/react";
import Head from "next/head";
import Image from "next/image";
import { HeaderImage } from "../components/Header/HeaderImage";
import { RotateButton } from "../components/Header/RotateButton";
import Navigation from "../components/Layout/Navigation";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Box p={{ base: "0px 20px", tablet: "0px 20px", desktop: "0px 40px" }}>
        <Navigation />
        <Flex p={"15vh 0px"} direction={{ base: "column", tablet: "row" }}>
          <Box width={{ base: "100vw", tablet: "50vw" }}>
            <Text>HOLA, ME DICEN</Text>
            <Text fontFamily={"Guttie, sans serif"} fontSize="120px">
              Mario
            </Text>
            <Text fontSize="25px">
              Desarrollador front end que disfruta de diseñar y plasmar ideas
              creativas en la web.
            </Text>
            {/* <RotateButton /> */}
          </Box>
          <Flex
            width={{ base: "100vw", tablet: "50vw" }}
            // display={{ base: "none", tablet: "flex" }}
            align="center"
            justify={"center"}
          >
            <Box position={"relative"} bottom={"150px"} left={"60px"}>
              <RotateButton />
            </Box>
            <HeaderImage width={"320px"} />
          </Flex>
        </Flex>
      </Box>
    </div>
  );
}
